Write-Output "安装 适用于Windows 10 LTSC 2021的Microsoft Store"
Write-Output ""
Write-Output "by GitHub @idhaname"
Write-Output "https://github.com/idhaname/LTSC2021-MSStore"
Write-Output ""
Write-Output "【注意】此安装程序仅适用于32位版本的Windows。"
Write-Output "64位版本请打开install_x64.ps1安装。"
Write-Output ""
Write-Output "要开始安装，请按指示继续"
pause
Write-Output "VCLibs..."
add-appxpackage "$PSScriptRoot\Microsoft.VCLibs.140.00_14.0.30704.0_x86__8wekyb3d8bbwe.Appx"
Write-Output "UI Xaml..."
add-appxpackage "$PSScriptRoot\Microsoft.UI.Xaml.2.7_7.2208.15002.0_x86__8wekyb3d8bbwe.Appx"
Write-Output ".NET Native Framework..."
add-appxpackage "$PSScriptRoot\Microsoft.NET.Native.Framework.2.2_2.2.29512.0_x86__8wekyb3d8bbwe.Appx"
Write-Output ".NET Native Runtime..."
add-appxpackage "$PSScriptRoot\Microsoft.NET.Native.Runtime.2.2_2.2.28604.0_x86__8wekyb3d8bbwe.Appx"
Write-Output "Microsoft Store..."
add-appxpackage "$PSScriptRoot\Microsoft.WindowsStore_22210.1401.10.0_neutral___8wekyb3d8bbwe.Msixbundle"
Write-Output "VCLibs UWPDesktop..."
add-appxpackage "$PSScriptRoot\Microsoft.VCLibs.140.00.UWPDesktop_14.0.30704.0_x86__8wekyb3d8bbwe.Appx"
Write-Output "应用安装程序..."
add-appxpackage "$PSScriptRoot\Microsoft.DesktopAppInstaller_2022.927.3.0_neutral___8wekyb3d8bbwe.Msixbundle"
Write-Output "StorePurchaseApp..."
add-appxpackage "$PSScriptRoot\Microsoft.StorePurchaseApp_12207.44.6.0_neutral___8wekyb3d8bbwe.AppxBundle"
Write-Output "Xbox Identity Provider..."
add-appxpackage "$PSScriptRoot\Microsoft.XboxIdentityProvider_12.95.3001.0_neutral___8wekyb3d8bbwe.AppxBundle"
Write-Output "安装完成！"
pause
exit
